services:
  nginx-iot:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx-iot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - NGINX_AUTORELOAD= #optional
      - NGINX_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - nginx-iot_config:/config
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped

volumes:
  nginx_config:
    driver_opts:
      type: "nfs"
      o: ${NGINX-IOT_NFS_PATH}
      device: ${NGINX-IOT_NFS_DEVICE_CONFIG}

networks:
  nginx-iot_internal:
  caddy-2_caddy_net:
    external: true